
POST https://localhost:7291/meals
Content-Type: application/json

{
  "name": "K",
  "description": "This keto pasta noodles recipe has just 2.7g net carbs and 3 ingredients!",
  "ingredients": [
    "2 cups Mozzarella Cheese",
    "4 large Egg Yolks",
    "1/2cup Lupin Flour"
  ],
  "calories": 248.7,
  "net_carbs": -2.7
}